### ISSUE TITLE
Suckin Grits on Root 66 Not working on Linux

### ISSUE THREAD

**Issue by vx-coupe** [nukeykt/Rednukem#4]
Compiled on Linux Mint19 Mate desktop. When I try to start the first or second episode it goes back to the menu. It appears to not find the level files, even though I have a sub directory called Route66 with the the level files in it (all executable) inside the directory with the rednukem binary.

to launch the game I typed -
./rednukem -x game66.con

Is it possible there is a hard coded directory structure for Windows?
I ask this as the error line has a back slash which is not normal for a Linux path.
Map "/Route66\Start.map" not found or invalid map version!

Here is the output of the log file -

Rednukem r(?)
Built Feb  2 2019 16:54:13, GCC 7.3.0, 64-bit 
Application parameters: -x game66.con 
Using CON file "game66.con".
Using /home/colin/Games/Rednukem2/ for game data
Using /home/colin/.config/rednukem/ for game data
Initializing SDL 2.0.8
Using "x11" video driver
Searching for game data...
Using "REDNECK.GRP" as main game data file.
Compiling: game66.con (30886 bytes)
Including: DEFS66.CON (24986 bytes)
Including: USER66.CON (38156 bytes)
Including: LEONARD.CON (9414 bytes)
Including: BILLY.CON (11369 bytes)
Including: HEN.CON (2282 bytes)
Including: COOT.CON (9530 bytes)
Including: GATOR66.CON (3213 bytes)
Including: COW.CON (3753 bytes)
Including: PIG66.CON (3345 bytes)
Including: MINION.CON (5157 bytes)
Including: HULK.CON (7719 bytes)
Including: TORNADO.CON (1815 bytes)
Including: SHERIFF.CON (8025 bytes)
Including: VIXEN.CON (15867 bytes)
VIXEN.CON: In actor `VIXEN':
VIXEN.CON:600: warning: `nullop' found without `else'
VIXEN.CON:668: warning: `nullop' found without `else'
VIXEN.CON:668: warning: empty `ifspritepal' branch
Including: BUBBA66.CON (5540 bytes)
BUBBA66.CON: In actor `BUBBASTAND':
BUBBA66.CON:215: warning: `nullop' found without `else'
Including: DOG.CON (4400 bytes)
Including: CRICKETC.CON (2474 bytes)
Including: TURDBOSS.CON (7723 bytes)
Found 4 warning(s), 0 error(s).
Script compiled in 15ms, 99976 bytes
Initialized 96.0M cache
RTS file "REDNECK.RTS" loaded
Initializing OSD...
0 joystick(s) found
Executing "settings.cfg"
Setting video mode 1920x1080 (32-bpp fullscreen)
Refresh rate: 60Hz
OpenGL information
 NVIDIA Corporation GeForce GTS 450/PCIe/SSE2 4.4.0 NVIDIA 340.107
Opened "textures" as cache file
Initializing music...
Initializing sound... 64 voices, 2 channels, 16-bit 48000 Hz
Sound flush.voc(#79) not found!
Sound grind.voc(#148) not found!
Sound g_sit.voc(#438) not found!
Sound g_bite.voc(#439) not found!
Sound whisper.voc(#442) not found!
Sound droppie.voc(#460) not found!
WARNING: invalid sound #213
Map "/Route66\Start.map" not found or invalid map version!
 
Wrote rednukem.cfg
Wrote settings.cfg

**Comment by nukeykt** [comment]
This is probably because linux is case sensitive. Make sure that folder/map names case is matches to definitions in CON file

**Comment by vx-coupe** [comment]
I modified USER66.CON as this was where the levels were list and it was straight from the Windows CD.

The levels were in the following format -

e.g.
Route66\Start.map

So I changed all the back slashes to forward slashes -

e.g.
Route66/Start.map

This worked! Thanks for your help as I wasn't sure where to look to fix this.
